package c2;

import com.bigbee.bean.request.PlayError;
import com.bigbee.bean.request.PlayFile;
import com.bigbee.bean.request.PlayMedia;
import com.bigbee.bean.request.PlayProgram;
import com.bigbee.bean.request.SwitchPlayer;
import com.google.firebase.dynamiclinks.DynamicLink;
import com.google.firebase.messaging.Constants;
import com.hpplay.component.common.ParamsMap;
import com.hpplay.component.protocol.push.IPushHandler;
import com.taobao.accs.common.Constants;
import com.taobao.accs.utl.BaseMonitor;
import com.umeng.analytics.pro.bt;
import java.util.HashMap;
import java.util.Locale;
import t9.i;
import tv.danmaku.ijk.media.player.IjkMediaMeta;

public final class f {

    /* renamed from: a  reason: collision with root package name */
    public static final f f4630a = new f();

    public final void a(PlayError playError, long j10, long j11) {
        i.g(playError, "playError");
        HashMap hashMap = new HashMap();
        String app = playError.getApp();
        i.f(app, "playError.app");
        hashMap.put("app", app);
        String app_ver = playError.getApp_ver();
        i.f(app_ver, "playError.app_ver");
        hashMap.put("app_ver", app_ver);
        String titan_ver = playError.getTitan_ver();
        i.f(titan_ver, "playError.titan_ver");
        hashMap.put("titan_ver", titan_ver);
        String uid = playError.getUid();
        i.f(uid, "playError.uid");
        hashMap.put(ParamsMap.DeviceParams.KEY_UID, uid);
        String sn = playError.getSn();
        i.f(sn, "playError.sn");
        hashMap.put("sn", sn);
        String model = playError.getModel();
        i.f(model, "playError.model");
        hashMap.put(Constants.KEY_MODEL, model);
        hashMap.put("sys_ver", l.f4666a.b().getSysVer());
        hashMap.put("instance", Integer.valueOf(playError.getInstance()));
        String program = playError.getProgram();
        i.f(program, "playError.program");
        hashMap.put("program", program);
        String title = playError.getTitle();
        i.f(title, "playError.title");
        hashMap.put("title", title);
        String episode = playError.getEpisode();
        i.f(episode, "playError.episode");
        hashMap.put("episode", episode);
        String buss = playError.getBuss();
        i.f(buss, "playError.buss");
        hashMap.put("buss", buss);
        String media = playError.getMedia();
        i.f(media, "playError.media");
        hashMap.put("media", media);
        String session = playError.getSession();
        i.f(session, "playError.session");
        hashMap.put("session", session);
        String lang = playError.getLang();
        String str = "";
        if (lang == null) {
            lang = str;
        }
        hashMap.put("lang", lang);
        String quality = playError.getQuality();
        if (quality != null) {
            str = quality;
        }
        hashMap.put("quality", str);
        hashMap.put("size", Long.valueOf(playError.getSize()));
        hashMap.put("media_duration", Long.valueOf(playError.getMedia_duration()));
        String format = playError.getFormat();
        i.f(format, "playError.format");
        hashMap.put(IjkMediaMeta.IJKM_KEY_FORMAT, format);
        String vcodec = playError.getVcodec();
        i.f(vcodec, "playError.vcodec");
        hashMap.put("vcodec", vcodec);
        String vdecoder = playError.getVdecoder();
        i.f(vdecoder, "playError.vdecoder");
        hashMap.put("vdecoder", vdecoder);
        String acodec = playError.getAcodec();
        i.f(acodec, "playError.acodec");
        hashMap.put("acodec", acodec);
        String params = playError.getParams();
        i.f(params, "playError.params");
        hashMap.put("params", params);
        String rule = playError.getRule();
        i.f(rule, "playError.rule");
        hashMap.put("rule", rule);
        String links = playError.getLinks();
        i.f(links, "playError.links");
        hashMap.put("links", links);
        String proxy = playError.getProxy();
        i.f(proxy, "playError.proxy");
        hashMap.put("proxy", proxy);
        String net_type = playError.getNet_type();
        i.f(net_type, "playError.net_type");
        hashMap.put("net_type", net_type);
        String player = playError.getPlayer();
        i.f(player, "playError.player");
        hashMap.put("player", player);
        hashMap.put("duration", Long.valueOf(playError.getDuration()));
        hashMap.put("play_duration", Long.valueOf(playError.getPlay_duration()));
        hashMap.put("seek_count", Long.valueOf(playError.getSeek_count()));
        hashMap.put("switch_count", Long.valueOf(playError.getSwitch_count()));
        hashMap.put("link_count", Long.valueOf(playError.getLink_count()));
        hashMap.put("replay_count", Long.valueOf(playError.getReplay_count()));
        String link = playError.getLink();
        i.f(link, "playError.link");
        hashMap.put(DynamicLink.Builder.KEY_LINK, link);
        String cdn_type = playError.getCdn_type();
        i.f(cdn_type, "playError.cdn_type");
        hashMap.put("cdn_type", cdn_type);
        String group = playError.getGroup();
        i.f(group, "playError.group");
        hashMap.put("group", group);
        String host = playError.getHost();
        i.f(host, "playError.host");
        hashMap.put(Constants.KEY_HOST, host);
        String idc = playError.getIdc();
        i.f(idc, "playError.idc");
        hashMap.put("idc", idc);
        String dns = playError.getDns();
        i.f(dns, "playError.dns");
        hashMap.put(BaseMonitor.COUNT_POINT_DNS, dns);
        String host_ip = playError.getHost_ip();
        i.f(host_ip, "playError.host_ip");
        hashMap.put("host_ip", host_ip);
        String protocol = playError.getProtocol();
        i.f(protocol, "playError.protocol");
        hashMap.put("protocol", protocol);
        hashMap.put("err", Long.valueOf(playError.getErr()));
        String codec_list = playError.getCodec_list();
        i.f(codec_list, "playError.codec_list");
        hashMap.put("codec_list", codec_list);
        if (playError.getReason() != null) {
            String reason = playError.getReason();
            i.f(reason, "playError.reason");
            hashMap.put(IPushHandler.REASON, reason);
        }
        e.f4622a.a("play_error", hashMap, j10, j11, false, true);
    }

    public final void b(PlayFile playFile, long j10, long j11) {
        i.g(playFile, "playFile");
        HashMap hashMap = new HashMap();
        String app = playFile.getApp();
        i.f(app, "playFile.app");
        hashMap.put("app", app);
        String app_ver = playFile.getApp_ver();
        i.f(app_ver, "playFile.app_ver");
        hashMap.put("app_ver", app_ver);
        String titan_ver = playFile.getTitan_ver();
        i.f(titan_ver, "playFile.titan_ver");
        hashMap.put("titan_ver", titan_ver);
        String uid = playFile.getUid();
        i.f(uid, "playFile.uid");
        hashMap.put(ParamsMap.DeviceParams.KEY_UID, uid);
        String sn = playFile.getSn();
        i.f(sn, "playFile.sn");
        hashMap.put("sn", sn);
        String model = playFile.getModel();
        i.f(model, "playFile.model");
        hashMap.put(Constants.KEY_MODEL, model);
        hashMap.put("sys_ver", l.f4666a.b().getSysVer());
        String program = playFile.getProgram();
        i.f(program, "playFile.program");
        hashMap.put("program", program);
        String media = playFile.getMedia();
        i.f(media, "playFile.media");
        hashMap.put("media", media);
        String title = playFile.getTitle();
        i.f(title, "playFile.title");
        hashMap.put("title", title);
        String buss = playFile.getBuss();
        i.f(buss, "playFile.buss");
        hashMap.put("buss", buss);
        String from = playFile.getFrom();
        i.f(from, "playFile.from");
        hashMap.put(Constants.MessagePayloadKeys.FROM, from);
        hashMap.put("duration", Long.valueOf(playFile.getDuration()));
        String player = playFile.getPlayer();
        i.f(player, "playFile.player");
        hashMap.put("player", player);
        hashMap.put("prepare_spent", Long.valueOf(playFile.getPrepare_spent()));
        hashMap.put("caton_count", Long.valueOf(playFile.getCaton_count()));
        hashMap.put("caton_duration", Long.valueOf(playFile.getCaton_duration()));
        String net_type = playFile.getNet_type();
        i.f(net_type, "playFile.net_type");
        hashMap.put("net_type", net_type);
        hashMap.put("err", Long.valueOf(playFile.getErr()));
        hashMap.put("PLAYER_RESET_COUNT", Long.valueOf(playFile.getPlayer_reset_count()));
        hashMap.put("recv_cache_bytes", Long.valueOf(playFile.getRecv_cache_bytes()));
        hashMap.put("recv_peer_bytes", Long.valueOf(playFile.getRecv_peer_bytes()));
        hashMap.put("recv_origin_tcp_bytes", Long.valueOf(playFile.getRecv_origin_tcp_bytes()));
        hashMap.put("recv_origin_cdp_bytes", Long.valueOf(playFile.getRecv_origin_cdp_bytes()));
        hashMap.put("read_cache_bytes", Long.valueOf(playFile.getRead_cache_bytes()));
        hashMap.put("send_peer_bytes", Long.valueOf(playFile.getSend_peer_bytes()));
        hashMap.put("player_repeat_req_count", Long.valueOf(playFile.getPlayer_repeat_req_count()));
        e.f4622a.a("play_file", hashMap, j10, j11, false, true);
    }

    public final void c(PlayMedia playMedia, long j10, long j11) {
        i.g(playMedia, "playMedia");
        HashMap hashMap = new HashMap();
        String app = playMedia.getApp();
        i.f(app, "playMedia.app");
        hashMap.put("app", app);
        String app_ver = playMedia.getApp_ver();
        i.f(app_ver, "playMedia.app_ver");
        hashMap.put("app_ver", app_ver);
        String titan_ver = playMedia.getTitan_ver();
        i.f(titan_ver, "playMedia.titan_ver");
        hashMap.put("titan_ver", titan_ver);
        String uid = playMedia.getUid();
        i.f(uid, "playMedia.uid");
        hashMap.put(ParamsMap.DeviceParams.KEY_UID, uid);
        String sn = playMedia.getSn();
        i.f(sn, "playMedia.sn");
        hashMap.put("sn", sn);
        String model = playMedia.getModel();
        i.f(model, "playMedia.model");
        hashMap.put(com.taobao.accs.common.Constants.KEY_MODEL, model);
        hashMap.put("sys_ver", l.f4666a.b().getSysVer());
        hashMap.put("instance", Integer.valueOf(playMedia.getInstance()));
        String program = playMedia.getProgram();
        i.f(program, "playMedia.program");
        hashMap.put("program", program);
        String title = playMedia.getTitle();
        i.f(title, "playMedia.title");
        hashMap.put("title", title);
        String episode = playMedia.getEpisode();
        i.f(episode, "playMedia.episode");
        hashMap.put("episode", episode);
        String buss = playMedia.getBuss();
        i.f(buss, "playMedia.buss");
        hashMap.put("buss", buss);
        String media = playMedia.getMedia();
        i.f(media, "playMedia.media");
        hashMap.put("media", media);
        String session = playMedia.getSession();
        i.f(session, "playMedia.session");
        hashMap.put("session", session);
        String lang = playMedia.getLang();
        String str = "";
        if (lang == null) {
            lang = str;
        }
        hashMap.put("lang", lang);
        String quality = playMedia.getQuality();
        if (quality != null) {
            str = quality;
        }
        hashMap.put("quality", str);
        hashMap.put("size", Long.valueOf(playMedia.getSize()));
        hashMap.put("media_duration", Long.valueOf(playMedia.getMedia_duration()));
        String format = playMedia.getFormat();
        i.f(format, "playMedia.format");
        hashMap.put(IjkMediaMeta.IJKM_KEY_FORMAT, format);
        String vcodec = playMedia.getVcodec();
        i.f(vcodec, "playMedia.vcodec");
        hashMap.put("vcodec", vcodec);
        String vdecoder = playMedia.getVdecoder();
        i.f(vdecoder, "playMedia.vdecoder");
        hashMap.put("vdecoder", vdecoder);
        String acodec = playMedia.getAcodec();
        i.f(acodec, "playMedia.acodec");
        hashMap.put("acodec", acodec);
        String params = playMedia.getParams();
        i.f(params, "playMedia.params");
        hashMap.put("params", params);
        String rule = playMedia.getRule();
        i.f(rule, "playMedia.rule");
        hashMap.put("rule", rule);
        String links = playMedia.getLinks();
        i.f(links, "playMedia.links");
        hashMap.put("links", links);
        String proxy = playMedia.getProxy();
        i.f(proxy, "playMedia.proxy");
        hashMap.put("proxy", proxy);
        String net_type = playMedia.getNet_type();
        i.f(net_type, "playMedia.net_type");
        hashMap.put("net_type", net_type);
        String player = playMedia.getPlayer();
        i.f(player, "playMedia.player");
        hashMap.put("player", player);
        hashMap.put("duration", Long.valueOf(playMedia.getDuration()));
        hashMap.put("play_duration", Long.valueOf(playMedia.getPlay_duration()));
        hashMap.put("seek_count", Long.valueOf(playMedia.getSeek_count()));
        hashMap.put("switch_count", Long.valueOf(playMedia.getSwitch_count()));
        hashMap.put("link_count", Long.valueOf(playMedia.getLink_count()));
        hashMap.put("replay_count", Long.valueOf(playMedia.getReplay_count()));
        hashMap.put("prepare_spent", Long.valueOf(playMedia.getPrepare_spent()));
        hashMap.put("link_spent", Long.valueOf(playMedia.getLink_spent()));
        hashMap.put("index_spent", Long.valueOf(playMedia.getIndex_spent()));
        hashMap.put("media_spent", Long.valueOf(playMedia.getMedia_spent()));
        hashMap.put("render_spent", Long.valueOf(playMedia.getRender_spent()));
        hashMap.put("caton_count", Long.valueOf(playMedia.getCaton_count()));
        hashMap.put("caton_duration", Long.valueOf(playMedia.getCaton_duration()));
        hashMap.put("net_caton_duration", Long.valueOf(playMedia.getNet_caton_duration()));
        hashMap.put("local_caton_duration", Long.valueOf(playMedia.getLocal_caton_duration()));
        hashMap.put("seek_caton_duration", Long.valueOf(playMedia.getSeek_caton_duration()));
        hashMap.put("origin_caton_duration", Long.valueOf(playMedia.getOrigin_caton_duration()));
        hashMap.put(bt.aZ, Long.valueOf(playMedia.getLatency()));
        hashMap.put("err", Long.valueOf(playMedia.getErr()));
        hashMap.put("PLAYER_RESET_COUNT", Long.valueOf(playMedia.getPlayer_reset_count()));
        hashMap.put("recv_cache_bytes", Long.valueOf(playMedia.getRecv_cache_bytes()));
        hashMap.put("recv_peer_bytes", Long.valueOf(playMedia.getRecv_peer_bytes()));
        hashMap.put("recv_origin_tcp_bytes", Long.valueOf(playMedia.getRecv_origin_tcp_bytes()));
        hashMap.put("recv_origin_cdp_bytes", Long.valueOf(playMedia.getRecv_origin_cdp_bytes()));
        hashMap.put("read_cache_bytes", Long.valueOf(playMedia.getRead_cache_bytes()));
        hashMap.put("send_peer_bytes", Long.valueOf(playMedia.getSend_peer_bytes()));
        hashMap.put("player_repeat_req_count", Long.valueOf(playMedia.getPlayer_repeat_req_count()));
        String codec_list = playMedia.getCodec_list();
        i.f(codec_list, "playMedia.codec_list");
        hashMap.put("codec_list", codec_list);
        String language = Locale.getDefault().getLanguage();
        i.f(language, "getDefault().language");
        hashMap.put("lang", language);
        if (playMedia.getNet_type() != null) {
            hashMap.put("nat_type", Integer.valueOf(playMedia.getNat_type()));
        }
        e.f4622a.a("play_media", hashMap, j10, j11, false, true);
    }

    public final void d(PlayProgram playProgram, long j10, long j11) {
        i.g(playProgram, "playProgram");
        HashMap hashMap = new HashMap();
        String app = playProgram.getApp();
        i.f(app, "playProgram.app");
        hashMap.put("app", app);
        String app_ver = playProgram.getApp_ver();
        i.f(app_ver, "playProgram.app_ver");
        hashMap.put("app_ver", app_ver);
        String titan_ver = playProgram.getTitan_ver();
        i.f(titan_ver, "playProgram.titan_ver");
        hashMap.put("titan_ver", titan_ver);
        String uid = playProgram.getUid();
        i.f(uid, "playProgram.uid");
        hashMap.put(ParamsMap.DeviceParams.KEY_UID, uid);
        String sn = playProgram.getSn();
        i.f(sn, "playProgram.sn");
        hashMap.put("sn", sn);
        String model = playProgram.getModel();
        i.f(model, "playProgram.model");
        hashMap.put(com.taobao.accs.common.Constants.KEY_MODEL, model);
        l lVar = l.f4666a;
        hashMap.put("sys_ver", lVar.b().getSysVer());
        String macAddr = lVar.b().getMacAddr();
        String str = "";
        if (macAddr == null) {
            macAddr = str;
        }
        hashMap.put(ParamsMap.DeviceParams.KEY_MAC, macAddr);
        String reserve1 = lVar.b().getReserve1();
        if (reserve1 != null) {
            str = reserve1;
        }
        hashMap.put("route_mac", str);
        hashMap.put("instance", Integer.valueOf(playProgram.getInstance()));
        String program = playProgram.getProgram();
        i.f(program, "playProgram.program");
        hashMap.put("program", program);
        String title = playProgram.getTitle();
        i.f(title, "playProgram.title");
        hashMap.put("title", title);
        String episode = playProgram.getEpisode();
        i.f(episode, "playProgram.episode");
        hashMap.put("episode", episode);
        String buss = playProgram.getBuss();
        i.f(buss, "playProgram.buss");
        hashMap.put("buss", buss);
        String session = playProgram.getSession();
        i.f(session, "playProgram.session");
        hashMap.put("session", session);
        String cause = playProgram.getCause();
        i.f(cause, "playProgram.cause");
        hashMap.put("cause", cause);
        String from = playProgram.getFrom();
        i.f(from, "playProgram.from");
        hashMap.put(Constants.MessagePayloadKeys.FROM, from);
        hashMap.put("duration", Long.valueOf(playProgram.getDuration()));
        hashMap.put("start", Long.valueOf(playProgram.getStart()));
        hashMap.put("switch_count", Long.valueOf(playProgram.getSwitch_count()));
        hashMap.put("media_duration", Long.valueOf(playProgram.getMedia_duration()));
        hashMap.put("prepare_spent", Long.valueOf(playProgram.getPrepare_spent()));
        hashMap.put("caton_count", Long.valueOf(playProgram.getCaton_count()));
        hashMap.put("caton_duration", Long.valueOf(playProgram.getCaton_duration()));
        String language = Locale.getDefault().getLanguage();
        i.f(language, "getDefault().language");
        hashMap.put("lang", language);
        e.f4622a.a("play_program", hashMap, j10, j11, false, true);
    }

    public final void e(SwitchPlayer switchPlayer, long j10, long j11) {
        i.g(switchPlayer, "switchPlayer");
        HashMap hashMap = new HashMap();
        String app = switchPlayer.getApp();
        i.f(app, "switchPlayer.app");
        hashMap.put("app", app);
        String app_ver = switchPlayer.getApp_ver();
        i.f(app_ver, "switchPlayer.app_ver");
        hashMap.put("app_ver", app_ver);
        String titan_ver = switchPlayer.getTitan_ver();
        i.f(titan_ver, "switchPlayer.titan_ver");
        hashMap.put("titan_ver", titan_ver);
        String uid = switchPlayer.getUid();
        i.f(uid, "switchPlayer.uid");
        hashMap.put(ParamsMap.DeviceParams.KEY_UID, uid);
        String sn = switchPlayer.getSn();
        i.f(sn, "switchPlayer.sn");
        hashMap.put("sn", sn);
        String model = switchPlayer.getModel();
        i.f(model, "switchPlayer.model");
        hashMap.put(com.taobao.accs.common.Constants.KEY_MODEL, model);
        hashMap.put("sys_ver", l.f4666a.b().getSysVer());
        String program = switchPlayer.getProgram();
        i.f(program, "switchPlayer.program");
        hashMap.put("program", program);
        String media = switchPlayer.getMedia();
        i.f(media, "switchPlayer.media");
        hashMap.put("media", media);
        String title = switchPlayer.getTitle();
        i.f(title, "switchPlayer.title");
        hashMap.put("title", title);
        String buss = switchPlayer.getBuss();
        i.f(buss, "switchPlayer.buss");
        hashMap.put("buss", buss);
        String from = switchPlayer.getFrom();
        i.f(from, "switchPlayer.from");
        hashMap.put(Constants.MessagePayloadKeys.FROM, from);
        String to = switchPlayer.getTo();
        i.f(to, "switchPlayer.to");
        hashMap.put("to", to);
        String format = switchPlayer.getFormat();
        i.f(format, "switchPlayer.format");
        hashMap.put(IjkMediaMeta.IJKM_KEY_FORMAT, format);
        String vcodec = switchPlayer.getVcodec();
        i.f(vcodec, "switchPlayer.vcodec");
        hashMap.put("vcodec", vcodec);
        hashMap.put("err", Long.valueOf(switchPlayer.getErr()));
        e.f4622a.a("switch_player", hashMap, j10, j11, false, true);
    }
}
